Repository adaptlearning/adapt-contrib-media, pull requests merged in 2025-03, with the labels that each got.

#318 Chore: Add support for new issue experience (fixes #315)
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: bug

#316 New: Migration scripts added to repo (fixes #314)
  migrations/v2.js
  migrations/v4.js
  migrations/v5.js
  migrations/v6.js
Labels: enhancement, ready to release

#313 Fix: "Skip to transcript" button spacing (fixes #312)
  less/media.less
Labels: bug, ready to release
